package levels;

import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import players.PlayerTree;
import sounds.SoundPlayer;
import sprites.Sprite;

/**
 * @date 5 September 2016
 * @version 0.2
 * @author Adriano Hernandez
 *
 * This will create a file that tells you it was created by level writer and
 * tells you how many sprites and playertrees (up to 1) and sounds there are, giving you
 * the paths for the sounds.
 */
public class LevelWriter {

	private String PATH;
	
	public LevelWriter() {
		this("C:\\Users\\" + 
			System.getProperty("user.name") + 
				"\\Documents\\MirrorGame\\LevelFiles\\mynewfile.txt");
	}
	public LevelWriter(String PATH) {
		this.PATH = PATH;
		// TODO Auto-generated constructor stub
	}
	public void writeFile(Level level){
		Path file = Paths.get(PATH);
		try {
			Files.write(file, getLines(level), Charset.forName("UTF-8"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	private List<String> getLines(Level level){
		List<String> list = new ArrayList<>();
		list.add("#####GENERATED BY FILE WRITER######");
		for(Sprite sp: level.getSprites()){
			list.add("sprite");
			//AND SOME MORE STUFF
		}
		if(level.getTree() != null) list.add("playertree");
		for(SoundPlayer snd: level.getSounds()){
			if(snd.getPath() == null || snd.getPath() == "") list.add("sound $unknownpath");
			else list.add("sound " + snd.getPath());
		}
		return list;
	}
	
	//getters and setters
	public String getPATH() {
		return PATH;
	}
	public void setPATH(String pATH) {
		PATH = pATH;
	}

}
