package levels;

import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

public class LevelWriter {

	private String PATH;
	
	public LevelWriter() {
		this("C:\\Users\\" + 
			System.getProperty("user.name") + 
				"\\Documents\\MirrorGame\\LevelFiles\\mynewfile.txt");
	}
	public LevelWriter(String PATH) {
		this.PATH = PATH;
		// TODO Auto-generated constructor stub
	}
	public void writeFile(Level level){
		Path file = Paths.get(PATH);
		try {
			Files.write(file, getLines(level), Charset.forName("UTF-8"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	private List<String> getLines(Level level){
		List<String> list = new ArrayList<>();
		list.add("#####GENERATED BY FILE WRITER######");
		return list;
	}
	
	//getters and setters
	public String getPATH() {
		return PATH;
	}
	public void setPATH(String pATH) {
		PATH = pATH;
	}

}
